### PR TITLE
Add Installation section

### PR DESCRIPTION
**Pull request by feimosi**
It's not obvious that this package also requires `image-js`. It took me a while to debug it.

### CODE REVIEW

**Comment by jajoe** [comment]
Sorry about that. In the package.json I've seen that image-js is in the "devDependencies", instead of being in the "dependencies".

**Comment by jajoe** [comment]
Before I merge, could you just modify the package.json and put image-js and ml-distance in "dependencies" (there are currently in "devDependencies") please ?

**Comment by feimosi** [comment]
No problem, it's done. I've also updated `package-lock.json` with the latest npm.

**Comment by jajoe** [comment]
thx. I merge.

**Pull request merged**
